const dayjs = require('dayjs');
const EVENTS = require('../data/events');
const discountRepo = require('../repositories/discount-code.repository');

function isToday(dateString) {
    return dayjs().format('MM-DD') === dateString.replace('-', '-');
}

function isWithinDayRange(range) {
    const today = Number(dayjs().format('DD'));
    return today >= range[0] && today <= range[1];
}

async function generateEventVouchers() {
    const todayMatches = EVENTS.filter((ev) => {
        if (ev.date && isToday(ev.date)) return true;
        if (ev.dayRange && isWithinDayRange(ev.dayRange)) return true;
        return false;
    });

    for (const ev of todayMatches) {
        const code = `EVT_${ev.code}_${dayjs().format('YYYYMMDD')}`;

        const exists = await discountRepo.findByCode(code);
        if (exists) continue;

        await discountRepo.create({
            code,
            type: 'percent',
            percent: ev.discount,
            maxUses: ev.maxUses || 1,
            expiresAt: dayjs().endOf('day').toDate(),
            eventCode: ev.code,
            autoGenerated: true,
        });
    }
}

module.exports = {
    generateEventVouchers,
};
